include: package:lints/recommended.yaml
linter:
  rules:
    - prefer_single_quotes: true
    - public_member_api_docs: true
    - avoid_print: true
    - avoid_web_libraries_in_flutter: true
    - prefer_const_constructors: true
    - prefer_final_fields: true
    - prefer_const_literals_to_create_immutables: true
    - unnecessary_new: true
    - unnecessary_this: true
    - avoid_unnecessary_containers: true
    - avoid_renaming_method_parameters: true
    - prefer_is_empty: true
