name: evefrontier_api
description: Library for working with EVE Frontier online game api.
version: 0.0.3-alpha
homepage: https://dip.dev
issue_tracker: https://github.com/dip-dev-team/evefrontier-api/issues
repository: https://github.com/dip-dev-team/evefrontier-api

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  http: ^1.3.0
  collection: ^1.19.1
  chopper: ^8.1.0
  built_value: ^8.9.5
  built_collection: ^5.1.1
  chopper_built_value: ^3.0.3
  logging: ^1.3.0
  hive_ce: ^2.10.1

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15
  build_runner: ^2.4.15
  chopper_generator: ^8.1.0
  built_value_generator: ^8.9.5
  hive_ce_generator: ^1.8.2

topics:
  - game
  - api
  - eve
  - evefrontier

funding:
  - https://www.buymeacoffee.com/dip.dev
  - https://www.thanks.dev/dip-dev-info
